// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#ifndef _CONSOLE_UI_H
#define _CONSOLE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_LoadingScreen.h"
#include "ui_SettingsScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1272477160);    // assets/wifi-icon.png
LV_IMG_DECLARE(ui_img_251037204);    // assets/profile-icon.png
LV_IMG_DECLARE(ui_img_1661376575);    // assets/Pacman-icon.png
LV_IMG_DECLARE(ui_img_1120585613);    // assets/SpaceShooter-icon.png
LV_IMG_DECLARE(ui_img_empty_png);    // assets/empty.png
LV_IMG_DECLARE(ui_img_149127453);    // assets/icons8-more-100 (1).png
LV_IMG_DECLARE(ui_img_1026671933);    // assets/galery-icon.png
LV_IMG_DECLARE(ui_img_492035433);    // assets/shop-icon.png
LV_IMG_DECLARE(ui_img_1699803486);    // assets/sd-icon.png
LV_IMG_DECLARE(ui_img_912092668);    // assets/settings-icon.png
LV_IMG_DECLARE(ui_img_1287641181);    // assets/poweroff-icon.png

// FONTS
LV_FONT_DECLARE(ui_font_RobotoBold16);
LV_FONT_DECLARE(ui_font_RobotoLight16);
LV_FONT_DECLARE(ui_font_RobotoMedium14);
LV_FONT_DECLARE(ui_font_RobotoMedium16);
LV_FONT_DECLARE(ui_font_RobotoMedium18);
LV_FONT_DECLARE(ui_font_RobotoRegular14);
LV_FONT_DECLARE(ui_font_RobotoRegular16);
LV_FONT_DECLARE(ui_font_RobotoRegular18);
LV_FONT_DECLARE(ui_font_RobotoRegular20);
LV_FONT_DECLARE(ui_font_RobotoSemiBold16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
