// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#include "ui.h"
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <string.h>

// Variables para menús
static lv_obj_t *energy_menu = NULL;
static lv_obj_t *energy_btn_suspend = NULL;
static lv_obj_t *energy_btn_restart = NULL;
static lv_obj_t *energy_btn_shutdown = NULL;
static lv_obj_t *energy_btn_cancel = NULL;

// Declarar funciones externas
extern void restart_console(void);
extern void suspend_console(void);
extern void shutdown_console(void);

void energy_btn_cb(lv_event_t *e) {
  lv_obj_t *target = lv_event_get_target(e);

  if (target == energy_btn_suspend) {
    lv_label_set_text(ui_Label6, "Modo suspensión");
    suspend_console();

  } else if (target == energy_btn_restart) {
    lv_label_set_text(ui_Label6, "Reiniciando...");
    restart_console();

  } else if (target == energy_btn_shutdown) {
    lv_label_set_text(ui_Label6, "Apagando...");
    shutdown_console();
  }

  // Cerrar menú (si no es cancelar)
  if (target != energy_btn_cancel && energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
  }
}

void close_energy_menu(lv_event_t *e) {
  if (energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
  }
}

void Trigger_Game(lv_event_t *e, const char *binPath) {
  // Inicializar pantalla de carga
  ui_LoadingScreen_screen_init();
  lv_scr_load(ui_LoadingScreen);

  // Crear estructura OTAArgs dinámica
  OTAArgs *args = (OTAArgs *)malloc(sizeof(OTAArgs));
  if (!args) {
    lv_label_set_text(ui_Label6, "Error interno");
    return;
  }
  args->binPath = binPath;
  args->progressBar = ui_Bar2;

  // Crear tarea OTA
  BaseType_t result = xTaskCreate(otaTask, "OTA", 8192, args, 1, NULL);
  if (result != pdPASS) {
    lv_label_set_text(ui_Label6, "Error iniciando OTA");
    free(args);
  }
}

void Trigger_Game1(lv_event_t *e) { Trigger_Game(e, "/game1.bin"); }
void Trigger_Game2(lv_event_t *e) { Trigger_Game(e, "/game2.bin"); }

void settings_console(lv_event_t *e) {
  if (ui_SettingsScreen) {
    lv_scr_load_anim(ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                     false);
  }
}

void back_to_home(lv_event_t *e) {
  if (ui_Screen1) {
    lv_scr_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);
  }
}

void poweroff_console(lv_event_t *e) {
  if (energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
    return;
  }

  /* ---------- CONTENEDOR ---------- */
  energy_menu = lv_obj_create(lv_scr_act());
  lv_obj_set_size(energy_menu, 440, 200);
  lv_obj_center(energy_menu);
  lv_obj_set_style_bg_color(energy_menu, lv_color_hex(0x2B2B2B), 0);
  lv_obj_set_style_bg_opa(energy_menu, LV_OPA_COVER, 0);
  lv_obj_set_style_radius(energy_menu, 18, 0);
  lv_obj_set_style_border_width(energy_menu, 2, 0);
  lv_obj_set_style_border_color(energy_menu, lv_color_hex(0x606060), 0);

  /* ---------- TÍTULO ---------- */
  lv_obj_t *title = lv_label_create(energy_menu);
  lv_label_set_text(title, "OPCIONES DE ENERGIA");
  lv_obj_set_style_text_font(title, &lv_font_montserrat_16, 0);
  lv_obj_set_style_text_color(title, lv_color_white(), 0);
  lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 10);

  /* ---------- PARÁMETROS ---------- */
  int btn_w = 130;
  int btn_h = 52; // MÁS GORDITOS
  int spacing = 16;
  int total_w = (btn_w * 3) + (spacing * 2);
  int start_x = -total_w / 2 + btn_w / 2;

  /* ---------- FILA DE BOTONES ---------- */
  int row_y = 18;

  /* ---------- SUSPENDER ---------- */
  energy_btn_suspend = lv_btn_create(energy_menu);
  lv_obj_set_size(energy_btn_suspend, btn_w, btn_h);
  lv_obj_align(energy_btn_suspend, LV_ALIGN_CENTER, start_x, row_y);
  lv_obj_set_style_bg_color(energy_btn_suspend, lv_color_hex(0x3E3E3E), 0);
  lv_obj_set_style_radius(energy_btn_suspend, 14, 0);
  lv_obj_set_style_shadow_width(energy_btn_suspend, 14, 0);
  lv_obj_set_style_shadow_opa(energy_btn_suspend, LV_OPA_30, 0);
  lv_obj_add_event_cb(energy_btn_suspend, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl_suspend = lv_label_create(energy_btn_suspend);
  lv_label_set_text(lbl_suspend, "Suspender");
  lv_obj_set_style_text_font(lbl_suspend, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(lbl_suspend, lv_color_white(), 0);
  lv_obj_center(lbl_suspend);

  /* ---------- REINICIAR ---------- */
  energy_btn_restart = lv_btn_create(energy_menu);
  lv_obj_set_size(energy_btn_restart, btn_w, btn_h);
  lv_obj_align(energy_btn_restart, LV_ALIGN_CENTER, start_x + (btn_w + spacing),
               row_y);
  lv_obj_set_style_bg_color(energy_btn_restart, lv_color_hex(0x3E3E3E), 0);
  lv_obj_set_style_radius(energy_btn_restart, 14, 0);
  lv_obj_set_style_shadow_width(energy_btn_restart, 14, 0);
  lv_obj_set_style_shadow_opa(energy_btn_restart, LV_OPA_30, 0);
  lv_obj_add_event_cb(energy_btn_restart, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl_restart = lv_label_create(energy_btn_restart);
  lv_label_set_text(lbl_restart, "Reiniciar");
  lv_obj_set_style_text_font(lbl_restart, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(lbl_restart, lv_color_white(), 0);
  lv_obj_center(lbl_restart);

  /* ---------- APAGAR ---------- */
  energy_btn_shutdown = lv_btn_create(energy_menu);
  lv_obj_set_size(energy_btn_shutdown, btn_w, btn_h);
  lv_obj_align(energy_btn_shutdown, LV_ALIGN_CENTER,
               start_x + 2 * (btn_w + spacing), row_y);
  lv_obj_set_style_bg_color(energy_btn_shutdown, lv_color_hex(0x8A2A2A), 0);
  lv_obj_set_style_radius(energy_btn_shutdown, 14, 0);
  lv_obj_set_style_shadow_width(energy_btn_shutdown, 18, 0);
  lv_obj_set_style_shadow_opa(energy_btn_shutdown, LV_OPA_40, 0);
  lv_obj_add_event_cb(energy_btn_shutdown, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl_shutdown = lv_label_create(energy_btn_shutdown);
  lv_label_set_text(lbl_shutdown, "Apagar");
  lv_obj_set_style_text_font(lbl_shutdown, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(lbl_shutdown, lv_color_white(), 0);
  lv_obj_center(lbl_shutdown);

  /* ---------- CANCELAR (MÁS ABAJO) ---------- */
  energy_btn_cancel = lv_btn_create(energy_menu);
  lv_obj_set_size(energy_btn_cancel, 180, 42);
  lv_obj_align(energy_btn_cancel, LV_ALIGN_BOTTOM_MID, 0, -20); // MÁS ESPACIO
  lv_obj_set_style_bg_color(energy_btn_cancel, lv_color_hex(0x555555), 0);
  lv_obj_set_style_radius(energy_btn_cancel, 12, 0);
  lv_obj_set_style_shadow_width(energy_btn_cancel, 10, 0);
  lv_obj_add_event_cb(energy_btn_cancel, close_energy_menu, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl_cancel = lv_label_create(energy_btn_cancel);
  lv_label_set_text(lbl_cancel, "Cancelar");
  lv_obj_set_style_text_font(lbl_cancel, &lv_font_montserrat_14, 0);
  lv_obj_set_style_text_color(lbl_cancel, lv_color_white(), 0);
  lv_obj_center(lbl_cancel);
}
