// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#include "ui.h"
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <string.h>

// Variables para menús
static lv_obj_t *energy_menu = NULL;
static lv_obj_t *energy_btn_suspend = NULL;
static lv_obj_t *energy_btn_restart = NULL;
static lv_obj_t *energy_btn_shutdown = NULL;
static lv_obj_t *energy_btn_cancel = NULL;

// Declarar funciones externas
extern void restart_console(void);
extern void suspend_console(void);
extern void shutdown_console(void);

void energy_btn_cb(lv_event_t *e) {
  lv_obj_t *target = lv_event_get_target(e);

  if (target == energy_btn_suspend) {
    lv_label_set_text(ui_Label6, "Modo suspensión");
    suspend_console();

  } else if (target == energy_btn_restart) {
    lv_label_set_text(ui_Label6, "Reiniciando...");
    restart_console();

  } else if (target == energy_btn_shutdown) {
    lv_label_set_text(ui_Label6, "Apagando...");
    shutdown_console();
  }

  // Cerrar menú (si no es cancelar)
  if (target != energy_btn_cancel && energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
  }
}

void close_energy_menu(lv_event_t *e) {
  if (energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
  }
}

void Trigger_Game(lv_event_t *e, const char *binPath) {
  // Inicializar pantalla de carga
  ui_LoadingScreen_screen_init();
  lv_scr_load(ui_LoadingScreen);

  // Crear estructura OTAArgs dinámica
  OTAArgs *args = (OTAArgs *)malloc(sizeof(OTAArgs));
  if (!args) {
    lv_label_set_text(ui_Label6, "Error interno");
    return;
  }
  args->binPath = binPath;
  args->progressBar = ui_Bar2;

  // Crear tarea OTA
  BaseType_t result = xTaskCreate(otaTask, "OTA", 8192, args, 1, NULL);
  if (result != pdPASS) {
    lv_label_set_text(ui_Label6, "Error iniciando OTA");
    free(args);
  }
}

void Trigger_Game1(lv_event_t *e) { Trigger_Game(e, "/game1.bin"); }
void Trigger_Game2(lv_event_t *e) { Trigger_Game(e, "/game2.bin"); }

void settings_console(lv_event_t *e) {
  if (ui_SettingsScreen) {
    lv_scr_load_anim(ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0,
                     false);
  }
}

void back_to_home(lv_event_t *e) {
  if (ui_Screen1) {
    lv_scr_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, false);
  }
}

void poweroff_console(lv_event_t *e) {
  // 1. Si ya existe el menú, cerrarlo
  if (energy_menu) {
    lv_obj_del(energy_menu);
    energy_menu = NULL;
    return;
  }

  // 2. Contenedor principal modal (semi-transparente fondo)
  // Usamos una capa completa para bloquear clics fuera
  lv_obj_t *overlay = lv_obj_create(lv_scr_act());
  lv_obj_set_size(overlay, 480, 320);
  lv_obj_set_style_bg_color(overlay, lv_color_black(), 0);
  lv_obj_set_style_bg_opa(overlay, LV_OPA_50, 0);
  lv_obj_clear_flag(overlay, LV_OBJ_FLAG_SCROLLABLE);

  // Guardamos el overlay como el handle principal para poder borrarlo luego
  // (O podemos hacerlo hijo del energy_menu si preferimos, pero aqui
  // energy_menu será la ventana) Para simplificar con tu lógica existente,
  // energy_menu será la VENTANA y el overlay será su padre o simplemente
  // hacemos la ventana modal directa. Vamos a seguir tu patrón: energy_menu es
  // la ventana flotante.

  // Borramos el overlay temporal porque vamos a usar energy_menu como la
  // ventana centrada directamente
  lv_obj_del(overlay);

  // --- VENTANA PRINCIPAL ---
  energy_menu = lv_obj_create(lv_scr_act());
  lv_obj_set_size(energy_menu, 420, 200);
  lv_obj_center(energy_menu);

  // Estilo Glassmorphism / Dark Modern
  lv_obj_set_style_bg_color(energy_menu, lv_color_hex(0x1F1F1F), 0);
  lv_obj_set_style_bg_opa(energy_menu, LV_OPA_90,
                          0); // Ligeramente transparente
  lv_obj_set_style_border_color(energy_menu, lv_color_hex(0x444444), 0);
  lv_obj_set_style_border_width(energy_menu, 2, 0);
  lv_obj_set_style_radius(energy_menu, 16, 0);
  lv_obj_set_style_shadow_width(energy_menu, 40, 0);
  lv_obj_set_style_shadow_color(energy_menu, lv_color_black(), 0);
  lv_obj_set_style_shadow_opa(energy_menu, LV_OPA_50, 0);
  lv_obj_clear_flag(energy_menu, LV_OBJ_FLAG_SCROLLABLE);

  // --- TÍTULO ---
  lv_obj_t *title = lv_label_create(energy_menu);
  lv_label_set_text(title, "MENU DE ENERGIA");
  lv_obj_set_style_text_font(title, &ui_font_RobotoMedium18,
                             0); // Fuente más grande si posible
  lv_obj_set_style_text_color(title, lv_color_hex(0xFFFFFF), 0);
  lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 5);

  // --- CONTENEDOR DE BOTONES (Horizontal Flex) ---
  lv_obj_t *btn_cont = lv_obj_create(energy_menu);
  lv_obj_set_size(btn_cont, 380, 80);
  lv_obj_align(btn_cont, LV_ALIGN_CENTER, 0, 0);
  lv_obj_set_style_bg_opa(btn_cont, LV_OPA_TRANSP, 0);
  lv_obj_set_style_border_width(btn_cont, 0, 0);
  lv_obj_set_flex_flow(btn_cont, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(btn_cont, LV_FLEX_ALIGN_SPACE_BETWEEN,
                        LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(btn_cont, LV_OBJ_FLAG_SCROLLABLE);

  // --- BOTÓN 1: SUSPENDER ---
  energy_btn_suspend = lv_btn_create(btn_cont);
  lv_obj_set_size(energy_btn_suspend, 110, 60);
  lv_obj_set_style_bg_color(energy_btn_suspend, lv_color_hex(0x2C3E50),
                            0); // Azul oscuro
  lv_obj_set_style_radius(energy_btn_suspend, 12, 0);
  lv_obj_add_event_cb(energy_btn_suspend, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl1 = lv_label_create(energy_btn_suspend);
  lv_label_set_text(lbl1, "Sleep");
  lv_obj_set_style_text_align(lbl1, LV_TEXT_ALIGN_CENTER, 0);
  lv_obj_center(lbl1);

  // --- BOTÓN 2: REINICIAR ---
  energy_btn_restart = lv_btn_create(btn_cont);
  lv_obj_set_size(energy_btn_restart, 110, 60);
  lv_obj_set_style_bg_color(energy_btn_restart, lv_color_hex(0xD35400),
                            0); // Naranja
  lv_obj_set_style_radius(energy_btn_restart, 12, 0);
  lv_obj_add_event_cb(energy_btn_restart, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl2 = lv_label_create(energy_btn_restart);
  lv_label_set_text(lbl2, "Reset");
  lv_obj_set_style_text_align(lbl2, LV_TEXT_ALIGN_CENTER, 0);
  lv_obj_center(lbl2);

  // --- BOTÓN 3: APAGAR ---
  energy_btn_shutdown = lv_btn_create(btn_cont);
  lv_obj_set_size(energy_btn_shutdown, 110, 60);
  lv_obj_set_style_bg_color(energy_btn_shutdown, lv_color_hex(0xC0392B),
                            0); // Rojo
  lv_obj_set_style_radius(energy_btn_shutdown, 12, 0);
  lv_obj_add_event_cb(energy_btn_shutdown, energy_btn_cb, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl3 = lv_label_create(energy_btn_shutdown);
  lv_label_set_text(lbl3, "Off");
  lv_obj_set_style_text_align(lbl3, LV_TEXT_ALIGN_CENTER, 0);
  lv_obj_center(lbl3);

  // --- BOTÓN CANCELAR ---
  energy_btn_cancel = lv_btn_create(energy_menu);
  lv_obj_set_size(energy_btn_cancel, 120, 35);
  lv_obj_align(energy_btn_cancel, LV_ALIGN_BOTTOM_MID, 0, -10);
  lv_obj_set_style_bg_color(energy_btn_cancel, lv_color_hex(0x555555), 0);
  lv_obj_set_style_radius(energy_btn_cancel, 20, 0); // Más redondeado (píldora)
  lv_obj_add_event_cb(energy_btn_cancel, close_energy_menu, LV_EVENT_CLICKED,
                      NULL);

  lv_obj_t *lbl_cancel = lv_label_create(energy_btn_cancel);
  lv_label_set_text(lbl_cancel, "Cancelar");
  lv_obj_center(lbl_cancel);
}
