// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#include "ui.h"

lv_obj_t * ui_LoadingScreen = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Bar2 = NULL;
// event funtions

// build funtions

void ui_LoadingScreen_screen_init(void)
{
    ui_LoadingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoadingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LoadingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LoadingScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_LoadingScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -11);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LOADING...");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_LoadingScreen);
    lv_obj_set_width(ui_Bar2, 237);
    lv_obj_set_height(ui_Bar2, 22);
    lv_obj_set_x(ui_Bar2, 3);
    lv_obj_set_y(ui_Bar2, 44);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);

}

void ui_LoadingScreen_screen_destroy(void)
{
    if(ui_LoadingScreen) lv_obj_del(ui_LoadingScreen);

    // NULL screen variables
    ui_LoadingScreen = NULL;
    ui_Label6 = NULL;
    ui_Bar2 = NULL;

}
