// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label3;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label2;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_ImgButton8;
extern void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern void ui_event_ImgButton11(lv_event_t * e);
extern lv_obj_t * ui_ImgButton11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

