// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ImgButton3 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ImgButton5 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_ImgButton4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_ImgButton9 = NULL;
lv_obj_t * ui_ImgButton7 = NULL;
lv_obj_t * ui_ImgButton8 = NULL;
lv_obj_t * ui_ImgButton10 = NULL;
lv_obj_t * ui_ImgButton11 = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Trigger_Game1(e);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Trigger_Game2(e);
    }
}

void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        settings_console(e);
    }
}

void ui_event_ImgButton11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        poweroff_console(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 480);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_align(ui_Container1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, 50);
    lv_obj_set_height(ui_Label1, 20);
    lv_obj_set_x(ui_Label1, 90);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "14:20");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_RobotoRegular18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image1, &ui_img_1272477160);
    lv_obj_set_width(ui_Image1, 20);
    lv_obj_set_height(ui_Image1, 20);
    lv_obj_set_x(ui_Image1, 143);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 300);

    ui_Bar1 = lv_bar_create(ui_Container1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 30);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 195);
    lv_obj_set_y(ui_Bar1, 0);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Bar1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Bar1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image2, &ui_img_251037204);
    lv_obj_set_width(ui_Image2, 30);
    lv_obj_set_height(ui_Image2, 30);
    lv_obj_set_x(ui_Image2, -210);
    lv_obj_set_y(ui_Image2, 0);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 300);

    ui_Container2 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 460);
    lv_obj_set_height(ui_Container2, 150);
    lv_obj_set_x(ui_Container2, 12);
    lv_obj_set_y(ui_Container2, -26);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_add_flag(ui_Container2, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Container2, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_Container2, LV_SCROLL_SNAP_START);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 135);
    lv_obj_set_height(ui_Container3, 150);
    lv_obj_set_x(ui_Container3, 5);
    lv_obj_set_y(ui_Container3, 58);
    lv_obj_set_align(ui_Container3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label3, 165);
    lv_obj_set_height(ui_Label3, 18);
    lv_obj_set_align(ui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Label3, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label3, "PAC-MAN");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_RobotoMedium18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imgbtn_create(ui_Container3);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1661376575, NULL);
    lv_imgbtn_set_src(ui_ImgButton1, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1661376575, NULL);
    lv_obj_set_width(ui_ImgButton1, 120);
    lv_obj_set_height(ui_ImgButton1, 120);
    lv_obj_set_x(ui_ImgButton1, 0);
    lv_obj_set_y(ui_ImgButton1, -5);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_ImgButton1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton1, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ImgButton1, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImgButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImgButton1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton1, 6, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton1, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container4 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 135);
    lv_obj_set_height(ui_Container4, 150);
    lv_obj_set_x(ui_Container4, 5);
    lv_obj_set_y(ui_Container4, 58);
    lv_obj_set_align(ui_Container4, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label2, 165);
    lv_obj_set_height(ui_Label2, 18);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label2, "Space Shooter");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_RobotoMedium18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Container4);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1120585613, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1120585613, NULL);
    lv_obj_set_width(ui_ImgButton2, 120);
    lv_obj_set_height(ui_ImgButton2, 120);
    lv_obj_set_x(ui_ImgButton2, 0);
    lv_obj_set_y(ui_ImgButton2, -5);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_ImgButton2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton2, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton2, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ImgButton2, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImgButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImgButton2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton2, 6, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton2, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container5 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 135);
    lv_obj_set_height(ui_Container5, 150);
    lv_obj_set_x(ui_Container5, 5);
    lv_obj_set_y(ui_Container5, 58);
    lv_obj_set_align(ui_Container5, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label4, 165);
    lv_obj_set_height(ui_Label4, 18);
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Label4, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label4, "");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_RobotoMedium18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_Container5);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_empty_png, NULL);
    lv_obj_set_width(ui_ImgButton3, 120);
    lv_obj_set_height(ui_ImgButton3, 120);
    lv_obj_set_x(ui_ImgButton3, 0);
    lv_obj_set_y(ui_ImgButton3, -5);
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_ImgButton3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton3, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton3, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ImgButton3, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImgButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImgButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImgButton3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton3, 6, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton3, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container7 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 135);
    lv_obj_set_height(ui_Container7, 150);
    lv_obj_set_x(ui_Container7, 5);
    lv_obj_set_y(ui_Container7, 58);
    lv_obj_set_align(ui_Container7, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label5, 165);
    lv_obj_set_height(ui_Label5, 18);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label5, "");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_RobotoMedium18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton5 = lv_imgbtn_create(ui_Container7);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_empty_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_empty_png, NULL);
    lv_obj_set_width(ui_ImgButton5, 120);
    lv_obj_set_height(ui_ImgButton5, 120);
    lv_obj_set_x(ui_ImgButton5, 0);
    lv_obj_set_y(ui_ImgButton5, -5);
    lv_obj_set_align(ui_ImgButton5, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_ImgButton5, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton5, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton5, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ImgButton5, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImgButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImgButton5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImgButton5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton5, 6, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton5, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container6 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 135);
    lv_obj_set_height(ui_Container6, 150);
    lv_obj_set_x(ui_Container6, 5);
    lv_obj_set_y(ui_Container6, 58);
    lv_obj_set_align(ui_Container6, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgButton4 = lv_imgbtn_create(ui_Container6);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_149127453, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_149127453, NULL);
    lv_obj_set_width(ui_ImgButton4, 120);
    lv_obj_set_height(ui_ImgButton4, 120);
    lv_obj_set_x(ui_ImgButton4, 0);
    lv_obj_set_y(ui_ImgButton4, -5);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_ImgButton4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton4, lv_color_hex(0x828282), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton4, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ImgButton4, lv_color_hex(0x4BC2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ImgButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ImgButton4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ImgButton4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton4, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton4, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 330);
    lv_obj_set_height(ui_Panel2, 44);
    lv_obj_set_x(ui_Panel2, 5);
    lv_obj_set_y(ui_Panel2, 99);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x6C6C6C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton9 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1026671933, NULL);
    lv_imgbtn_set_src(ui_ImgButton9, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1026671933, NULL);
    lv_obj_set_width(ui_ImgButton9, 32);
    lv_obj_set_height(ui_ImgButton9, 32);
    lv_obj_set_align(ui_ImgButton9, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton9, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton9, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton9, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton9, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton7 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_492035433, NULL);
    lv_imgbtn_set_src(ui_ImgButton7, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_492035433, NULL);
    lv_obj_set_width(ui_ImgButton7, 32);
    lv_obj_set_height(ui_ImgButton7, 32);
    lv_obj_set_align(ui_ImgButton7, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton7, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton7, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton7, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton8 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1699803486, NULL);
    lv_imgbtn_set_src(ui_ImgButton8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1699803486, NULL);
    lv_obj_set_width(ui_ImgButton8, 32);
    lv_obj_set_height(ui_ImgButton8, 32);
    lv_obj_set_align(ui_ImgButton8, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton8, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton8, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton8, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton8, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton10 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_912092668, NULL);
    lv_imgbtn_set_src(ui_ImgButton10, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_912092668, NULL);
    lv_obj_set_width(ui_ImgButton10, 32);
    lv_obj_set_height(ui_ImgButton10, 32);
    lv_obj_set_align(ui_ImgButton10, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton10, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton10, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton10, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton10, true, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImgButton11 = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1287641181, NULL);
    lv_imgbtn_set_src(ui_ImgButton11, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_1287641181, NULL);
    lv_obj_set_width(ui_ImgButton11, 32);
    lv_obj_set_height(ui_ImgButton11, 32);
    lv_obj_set_align(ui_ImgButton11, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton11, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ImgButton11, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ImgButton11, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_clip_corner(ui_ImgButton11, true, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton10, ui_event_ImgButton10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton11, ui_event_ImgButton11, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Container1 = NULL;
    ui_Label1 = NULL;
    ui_Image1 = NULL;
    ui_Bar1 = NULL;
    ui_Image2 = NULL;
    ui_Container2 = NULL;
    ui_Container3 = NULL;
    ui_Label3 = NULL;
    ui_ImgButton1 = NULL;
    ui_Container4 = NULL;
    ui_Label2 = NULL;
    ui_ImgButton2 = NULL;
    ui_Container5 = NULL;
    ui_Label4 = NULL;
    ui_ImgButton3 = NULL;
    ui_Container7 = NULL;
    ui_Label5 = NULL;
    ui_ImgButton5 = NULL;
    ui_Container6 = NULL;
    ui_ImgButton4 = NULL;
    ui_Panel2 = NULL;
    ui_ImgButton9 = NULL;
    ui_ImgButton7 = NULL;
    ui_ImgButton8 = NULL;
    ui_ImgButton10 = NULL;
    ui_ImgButton11 = NULL;

}
