// This file was generated by SquareLine Studio (Modified)
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: Console

#include "ui_SettingsScreen.h"
#include "ui.h"
#include "ui_events.h"

// --- GLOBALS ---
lv_obj_t *ui_SettingsScreen = NULL;
lv_obj_t *ui_Container9 = NULL;
lv_obj_t *ui_Label8 = NULL;
lv_obj_t *ui_Image5 = NULL;
lv_obj_t *ui_Bar4 = NULL;
lv_obj_t *ui_BtnBack = NULL;
lv_obj_t *ui_LabelBack = NULL;

// Panels
lv_obj_t *ui_PanelEnergy = NULL;
lv_obj_t *ui_PanelDebug = NULL;
lv_obj_t *ui_PanelWifi = NULL;

// Energy Elements
lv_obj_t *ui_BtnSuspend = NULL;
lv_obj_t *ui_BtnRestart = NULL;
lv_obj_t *ui_BtnShutdown = NULL;
lv_obj_t *ui_LabelSuspend = NULL;
lv_obj_t *ui_LabelRestart = NULL;
lv_obj_t *ui_LabelShutdown = NULL;

// Debug Elements
lv_obj_t *ui_LabelDebug = NULL;

// Wifi Elements
lv_obj_t *ui_WifiList = NULL;       // List for networks
lv_obj_t *ui_WifiPass = NULL;       // Password input
lv_obj_t *ui_WifiConnectBtn = NULL; // Connect Button
lv_obj_t *ui_WifiScanBtn = NULL;    // Scan Button
lv_obj_t *ui_WifiKeyboard = NULL;   // Screen Keyboard

extern void back_to_home(lv_event_t *e);
extern void suspend_console(void);
extern void restart_console(void);
extern void shutdown_console(void);

// Events for Energy
static void event_suspend(lv_event_t *e) { suspend_console(); }
static void event_restart(lv_event_t *e) { restart_console(); }
static void event_shutdown(lv_event_t *e) { shutdown_console(); }

// Tab Switching Callback
static void _tab_switch_cb(lv_event_t *e) {
  lv_obj_t *target_panel = (lv_obj_t *)lv_event_get_user_data(e);

  // Hide all panels
  if (ui_PanelEnergy)
    lv_obj_add_flag(ui_PanelEnergy, LV_OBJ_FLAG_HIDDEN);
  if (ui_PanelDebug)
    lv_obj_add_flag(ui_PanelDebug, LV_OBJ_FLAG_HIDDEN);
  if (ui_PanelWifi)
    lv_obj_add_flag(ui_PanelWifi, LV_OBJ_FLAG_HIDDEN);

  // Show target panel
  if (target_panel)
    lv_obj_clear_flag(target_panel, LV_OBJ_FLAG_HIDDEN);
}

// Keyboard Logic
static void _wifi_kb_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  lv_obj_t *kb = lv_event_get_target(e);
  if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
    lv_obj_add_flag(kb, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_state(ui_WifiPass, LV_STATE_FOCUSED);
  }
}

static void _wifi_ta_event_cb(lv_event_t *e) {
  lv_event_code_t code = lv_event_get_code(e);
  if (code == LV_EVENT_CLICKED || code == LV_EVENT_FOCUSED) {
    if (ui_WifiKeyboard) {
      lv_keyboard_set_textarea(ui_WifiKeyboard, ui_WifiPass);
      lv_obj_clear_flag(ui_WifiKeyboard, LV_OBJ_FLAG_HIDDEN);
      lv_obj_move_foreground(ui_WifiKeyboard);
    }
  }
}

// Declaración de las funciones WiFi (se implementan en el .ino)
extern void wifi_scan_click(lv_event_t *e);
extern void wifi_connect_click(lv_event_t *e);

void ui_SettingsScreen_screen_init(void) {
  ui_SettingsScreen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x101010),
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  // --- TOP BAR (Similar to Screen1) ---
  ui_Container9 = lv_obj_create(ui_SettingsScreen);
  lv_obj_remove_style_all(ui_Container9);
  lv_obj_set_width(ui_Container9, 480);
  lv_obj_set_height(ui_Container9, 50);
  lv_obj_set_align(ui_Container9, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_Container9,
                    LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  // Botón Back
  ui_BtnBack = lv_btn_create(ui_Container9);
  lv_obj_set_width(ui_BtnBack, 80);
  lv_obj_set_height(ui_BtnBack, 36);
  lv_obj_set_x(ui_BtnBack, 10);
  lv_obj_set_align(ui_BtnBack, LV_ALIGN_LEFT_MID);
  lv_obj_set_style_bg_color(ui_BtnBack, lv_color_hex(0x404040), 0);
  lv_obj_add_event_cb(ui_BtnBack, back_to_home, LV_EVENT_CLICKED, NULL);

  ui_LabelBack = lv_label_create(ui_BtnBack);
  lv_label_set_text(ui_LabelBack, "< BACK");
  lv_obj_center(ui_LabelBack);

  ui_Label8 = lv_label_create(ui_Container9);
  lv_obj_set_width(ui_Label8, 100);
  lv_obj_set_height(ui_Label8, 20);
  lv_obj_set_x(ui_Label8, 110);
  lv_obj_set_align(ui_Label8, LV_ALIGN_LEFT_MID);
  lv_label_set_text(ui_Label8, "SETTINGS");
  lv_obj_set_style_text_font(ui_Label8, &ui_font_RobotoRegular18, 0);
  lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), 0);

  // Icono WiFi y Barra Bateria en Topbar
  ui_Image5 = lv_img_create(ui_Container9);
  lv_img_set_src(ui_Image5, &ui_img_1272477160);
  lv_obj_set_size(ui_Image5, 20, 20);
  lv_obj_set_align(ui_Image5, LV_ALIGN_RIGHT_MID);
  lv_obj_set_x(ui_Image5, -60);
  lv_img_set_zoom(ui_Image5, 300);

  ui_Bar4 = lv_bar_create(ui_Container9);
  lv_obj_set_size(ui_Bar4, 30, 10);
  lv_obj_set_align(ui_Bar4, LV_ALIGN_RIGHT_MID);
  lv_obj_set_x(ui_Bar4, -20);
  lv_obj_set_style_radius(ui_Bar4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), 0);
  lv_obj_set_style_bg_opa(ui_Bar4, 0, 0);
  lv_obj_set_style_outline_color(ui_Bar4, lv_color_hex(0xFFFFFF), 0);
  lv_obj_set_style_outline_width(ui_Bar4, 2, 0);
  lv_obj_set_style_outline_pad(ui_Bar4, 3, 0);
  lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR);

  // --- MAIN LAYOUT (Sidebar + Content) ---
  lv_obj_t *main_cont = lv_obj_create(ui_SettingsScreen);
  lv_obj_set_size(main_cont, 480, 270);
  lv_obj_set_y(main_cont, 50);
  lv_obj_set_style_bg_opa(main_cont, 0, 0);
  lv_obj_set_style_border_width(main_cont, 0, 0);
  lv_obj_set_style_pad_all(main_cont, 0, 0);

  // --- SIDEBAR ---
  lv_obj_t *sidebar = lv_obj_create(main_cont);
  lv_obj_set_size(sidebar, 120, 270);
  lv_obj_set_align(sidebar, LV_ALIGN_TOP_LEFT);
  lv_obj_set_style_bg_color(sidebar, lv_color_hex(0x202020), 0);
  lv_obj_set_style_border_side(sidebar, LV_BORDER_SIDE_RIGHT, 0);
  lv_obj_set_style_border_color(sidebar, lv_color_hex(0x444444), 0);
  lv_obj_set_style_radius(sidebar, 0, 0);
  lv_obj_set_flex_flow(sidebar, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_style_pad_all(sidebar, 10, 0);
  lv_obj_set_style_pad_gap(sidebar, 15, 0);

  // Helper to create Sidebar Buttons
  lv_obj_t *btn;
  lv_obj_t *lbl;

  // 1. Energy Button
  btn = lv_btn_create(sidebar);
  lv_obj_set_width(btn, 100);
  lv_obj_set_height(btn, 40);
  lv_obj_set_style_bg_color(btn, lv_color_hex(0x404040), 0);
  lbl = lv_label_create(btn);
  lv_label_set_text(lbl, "Energia");
  lv_obj_center(lbl);
  lv_obj_add_event_cb(btn, _tab_switch_cb, LV_EVENT_CLICKED, NULL);
  lv_obj_set_user_data(btn, ui_PanelEnergy); // Se actualizará después

  // 2. Debug Button
  lv_obj_t *btn_debug = lv_btn_create(sidebar);
  lv_obj_set_width(btn_debug, 100);
  lv_obj_set_height(btn_debug, 40);
  lv_obj_set_style_bg_color(btn_debug, lv_color_hex(0x404040), 0);
  lbl = lv_label_create(btn_debug);
  lv_label_set_text(lbl, "Debug");
  lv_obj_center(lbl);
  lv_obj_add_event_cb(btn_debug, _tab_switch_cb, LV_EVENT_CLICKED, NULL);
  lv_obj_set_user_data(btn_debug, ui_PanelDebug); // Se actualizará después

  // 3. WiFi Button
  lv_obj_t *btn_wifi = lv_btn_create(sidebar);
  lv_obj_set_width(btn_wifi, 100);
  lv_obj_set_height(btn_wifi, 40);
  lv_obj_set_style_bg_color(btn_wifi, lv_color_hex(0x404040), 0);
  lbl = lv_label_create(btn_wifi);
  lv_label_set_text(lbl, "WiFi");
  lv_obj_center(lbl);
  lv_obj_add_event_cb(btn_wifi, _tab_switch_cb, LV_EVENT_CLICKED, NULL);
  lv_obj_set_user_data(btn_wifi, ui_PanelWifi); // Se actualizará después

  // --- CONTENT AREA ---
  lv_obj_t *content_area = lv_obj_create(main_cont);
  lv_obj_set_size(content_area, 360, 270);
  lv_obj_set_align(content_area, LV_ALIGN_TOP_RIGHT);
  lv_obj_set_style_bg_opa(content_area, 0, 0);
  lv_obj_set_style_border_width(content_area, 0, 0);
  lv_obj_set_style_pad_all(content_area, 10, 0);

  // ================= PANEL 1: ENERGY =================
  ui_PanelEnergy = lv_obj_create(content_area);
  lv_obj_set_size(ui_PanelEnergy, 340, 250);
  lv_obj_center(ui_PanelEnergy);
  lv_obj_set_style_bg_color(ui_PanelEnergy, lv_color_hex(0x181818), 0);
  lv_obj_set_flex_flow(ui_PanelEnergy, LV_FLEX_FLOW_ROW_WRAP);
  lv_obj_set_flex_align(ui_PanelEnergy, LV_FLEX_ALIGN_CENTER,
                        LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_set_style_pad_gap(ui_PanelEnergy, 20, 0);

  // Suspend
  ui_BtnSuspend = lv_btn_create(ui_PanelEnergy);
  lv_obj_set_size(ui_BtnSuspend, 140, 60);
  lv_obj_set_style_bg_color(ui_BtnSuspend, lv_color_hex(0x2C3E50), 0);
  ui_LabelSuspend = lv_label_create(ui_BtnSuspend);
  lv_label_set_text(ui_LabelSuspend, "Suspend");
  lv_obj_center(ui_LabelSuspend);
  lv_obj_add_event_cb(ui_BtnSuspend, event_suspend, LV_EVENT_CLICKED, NULL);

  // Restart
  ui_BtnRestart = lv_btn_create(ui_PanelEnergy);
  lv_obj_set_size(ui_BtnRestart, 140, 60);
  lv_obj_set_style_bg_color(ui_BtnRestart, lv_color_hex(0xD35400), 0);
  ui_LabelRestart = lv_label_create(ui_BtnRestart);
  lv_label_set_text(ui_LabelRestart, "Restart");
  lv_obj_center(ui_LabelRestart);
  lv_obj_add_event_cb(ui_BtnRestart, event_restart, LV_EVENT_CLICKED, NULL);

  // Shutdown
  ui_BtnShutdown = lv_btn_create(ui_PanelEnergy);
  lv_obj_set_size(ui_BtnShutdown, 140, 60);
  lv_obj_set_style_bg_color(ui_BtnShutdown, lv_color_hex(0xC0392B), 0);
  ui_LabelShutdown = lv_label_create(ui_BtnShutdown);
  lv_label_set_text(ui_LabelShutdown, "Shutdown");
  lv_obj_center(ui_LabelShutdown);
  lv_obj_add_event_cb(ui_BtnShutdown, event_shutdown, LV_EVENT_CLICKED, NULL);

  // Actualizar datos de los botones de sidebar
  lv_obj_set_user_data(btn, ui_PanelEnergy);

  // ================= PANEL 2: DEBUG =================
  ui_PanelDebug = lv_obj_create(content_area);
  lv_obj_set_size(ui_PanelDebug, 340, 250);
  lv_obj_center(ui_PanelDebug);
  lv_obj_set_style_bg_color(ui_PanelDebug, lv_color_hex(0x000000), 0);
  lv_obj_add_flag(ui_PanelDebug, LV_OBJ_FLAG_HIDDEN);

  ui_LabelDebug = lv_label_create(ui_PanelDebug);
  lv_obj_set_width(ui_LabelDebug, 320);
  lv_label_set_long_mode(ui_LabelDebug, LV_LABEL_LONG_WRAP);
  lv_label_set_text(ui_LabelDebug, "Cargando datos...");
  lv_obj_set_style_text_font(ui_LabelDebug, &lv_font_montserrat_12, 0);
  lv_obj_set_style_text_color(ui_LabelDebug, lv_color_hex(0x00FF00), 0);
  lv_obj_set_align(ui_LabelDebug, LV_ALIGN_TOP_LEFT);

  lv_obj_set_user_data(btn_debug, ui_PanelDebug);

  // ================= PANEL 3: WIFI (MEJORADO) =================
  ui_PanelWifi = lv_obj_create(content_area);
  lv_obj_set_size(ui_PanelWifi, 340, 250);
  lv_obj_center(ui_PanelWifi);
  lv_obj_set_style_bg_color(ui_PanelWifi, lv_color_hex(0x181818), 0);
  lv_obj_add_flag(ui_PanelWifi, LV_OBJ_FLAG_HIDDEN);

  // Contenedor principal WiFi
  lv_obj_t *wifi_container = lv_obj_create(ui_PanelWifi);
  lv_obj_set_size(wifi_container, 320, 240);
  lv_obj_center(wifi_container);
  lv_obj_set_style_bg_opa(wifi_container, 0, 0);
  lv_obj_set_style_border_width(wifi_container, 0, 0);
  lv_obj_set_flex_flow(wifi_container, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_style_pad_all(wifi_container, 5, 0);
  lv_obj_set_style_pad_gap(wifi_container, 10, 0);

  // 1. Fila de botones superiores
  lv_obj_t *btn_row = lv_obj_create(wifi_container);
  lv_obj_set_size(btn_row, 310, 45);
  lv_obj_set_style_bg_opa(btn_row, 0, 0);
  lv_obj_set_style_border_width(btn_row, 0, 0);
  lv_obj_set_flex_flow(btn_row, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(btn_row, LV_FLEX_ALIGN_SPACE_BETWEEN,
                        LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

  ui_WifiScanBtn = lv_btn_create(btn_row);
  lv_obj_set_size(ui_WifiScanBtn, 140, 40);
  lv_obj_set_style_bg_color(ui_WifiScanBtn, lv_color_hex(0x3498DB), 0);
  lv_obj_set_style_radius(ui_WifiScanBtn, 8, 0);
  lv_obj_add_event_cb(ui_WifiScanBtn, wifi_scan_click, LV_EVENT_CLICKED, NULL);
  lv_obj_t *scan_label = lv_label_create(ui_WifiScanBtn);
  lv_label_set_text(scan_label, LV_SYMBOL_REFRESH " SCAN");
  lv_obj_center(scan_label);

  ui_WifiConnectBtn = lv_btn_create(btn_row);
  lv_obj_set_size(ui_WifiConnectBtn, 140, 40);
  lv_obj_set_style_bg_color(ui_WifiConnectBtn, lv_color_hex(0x27AE60), 0);
  lv_obj_set_style_radius(ui_WifiConnectBtn, 8, 0);
  lv_obj_add_event_cb(ui_WifiConnectBtn, wifi_connect_click, LV_EVENT_CLICKED,
                      NULL);
  lv_obj_t *connect_label = lv_label_create(ui_WifiConnectBtn);
  lv_label_set_text(connect_label, LV_SYMBOL_OK " CONNECT");
  lv_obj_center(connect_label);

  // 2. Lista de redes WiFi (MUCHO más arriba)
  ui_WifiList = lv_list_create(wifi_container);
  lv_obj_set_size(ui_WifiList, 310, 120); // Más grande
  lv_obj_set_style_bg_color(ui_WifiList, lv_color_hex(0x252525), 0);
  lv_obj_set_style_border_color(ui_WifiList, lv_color_hex(0x444444), 0);
  lv_obj_set_style_border_width(ui_WifiList, 1, 0);
  lv_obj_set_style_radius(ui_WifiList, 6, 0);

  // 3. Campo de contraseña (visible mientras escribes)
  lv_obj_t *pass_container = lv_obj_create(wifi_container);
  lv_obj_set_size(pass_container, 310, 50);
  lv_obj_set_style_bg_opa(pass_container, 0, 0);
  lv_obj_set_style_border_width(pass_container, 0, 0);
  lv_obj_set_flex_flow(pass_container, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_style_pad_top(pass_container, 5, 0);

  lv_obj_t *pass_label = lv_label_create(pass_container);
  lv_label_set_text(pass_label, "CONTRASEÑA:");
  lv_obj_set_style_text_color(pass_label, lv_color_hex(0xAAAAAA), 0);
  lv_obj_set_style_text_font(pass_label, &ui_font_RobotoRegular14, 0);
  lv_obj_align(pass_label, LV_ALIGN_TOP_LEFT, 0, 0);

  ui_WifiPass = lv_textarea_create(pass_container);
  lv_textarea_set_one_line(ui_WifiPass, true);
  lv_textarea_set_password_mode(ui_WifiPass, true);
  lv_textarea_set_placeholder_text(ui_WifiPass,
                                   "Escribe la contraseña WiFi...");
  lv_obj_set_size(ui_WifiPass, 310, 35);
  lv_obj_set_y(ui_WifiPass, 20);
  lv_obj_set_style_bg_color(ui_WifiPass, lv_color_hex(0x303030), 0);
  lv_obj_set_style_border_color(ui_WifiPass, lv_color_hex(0x555555), 0);
  lv_obj_set_style_border_width(ui_WifiPass, 1, 0);
  lv_obj_set_style_radius(ui_WifiPass, 6, 0);
  lv_obj_set_style_pad_all(ui_WifiPass, 8, 0);
  lv_obj_add_event_cb(ui_WifiPass, _wifi_ta_event_cb, LV_EVENT_CLICKED, NULL);

  lv_obj_set_user_data(btn_wifi, ui_PanelWifi);

  // --- KEYBOARD (Global) ---
  ui_WifiKeyboard = lv_keyboard_create(ui_SettingsScreen);
  lv_obj_set_size(ui_WifiKeyboard, 480, 160);
  lv_obj_align(ui_WifiKeyboard, LV_ALIGN_BOTTOM_MID, 0, 0);
  lv_obj_add_flag(ui_WifiKeyboard, LV_OBJ_FLAG_HIDDEN);
  lv_obj_add_event_cb(ui_WifiKeyboard, _wifi_kb_event_cb, LV_EVENT_ALL, NULL);

  // Mostrar panel de energía por defecto
  lv_obj_clear_flag(ui_PanelEnergy, LV_OBJ_FLAG_HIDDEN);
}

void ui_SettingsScreen_screen_destroy(void) {
  if (ui_SettingsScreen)
    lv_obj_del(ui_SettingsScreen);
  ui_SettingsScreen = NULL;
}